apiVersion: apps/v1
kind: Deployment
metadata:
  name: azure-template
spec:
  replicas: 1
  selector:
    matchLabels:
      app: azure-template
  template:
    metadata:
      labels:
        app: azure-template
    spec:
      nodeSelector:
        "beta.kubernetes.io/os": linux
      containers:
      - name: azure-template
        image: ${{ secrets.REGISTRY_LOGIN_SERVER }}/azuretemplate:${{ github.sha }}
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 250m
            memory: 256Mi
        ports:
        - containerPort: 80
        env:
        - name: azure-template
          value: "azure-template"
---
apiVersion: v1
kind: Service
metadata:
  name: azure-template
spec:
  type: LoadBalancer
  ports:
  - port: 80
  selector:
    app: azure-template
